[build]
  command = "npm run build && netlify-lambda build functions/graphql"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/.netlify/functions/graphql"
  to = "/graphql"
  force = true
  status = 200